### ISSUE TITLE
Some TODO

### ISSUE THREAD

**Issue by saderror256** [saderror256/starcat#4]
- Make sure SQL injection is fixed (i forgot to test it this night)
- Add \<br\> at the end of all error messages
- Redirect to setup if starcat database not found
- Add in installer to wipe database. But the **problem** is that once the setup is done it will get removed so no one can overwrite stuff, but a password is required for that, for now, lets keep it safe.

**The only thing required to be done to get it working is just `chown apache:apache starcat` on the directory, and it will work fine. Check MySQL databases, and see tables.**

Also, I am going to split all contacts with a "," and append it on the table, because mysql takes a while to create tables for me, so i dont want to create a table for every specific user listing it all in a nice (but surely bloated) order, since its an illegal character name, anyway. or maybe a different character

**Comment by emilengler** [comment]
Point 4 can be handled like this:

- Create a function to wipe the database
- When the installer starts, it checks if a specifc file exists
- If the text file not exists, execute the wiping function and then create the text file
- If the text file exists do not execute the function

`function wipe_db($conn) {
//Some mysql statements
}`

`if(file_exists('setup_done.txt') {
die('Starcat is already setted up');
}
else {
wipe_db($conn);
$setup_done_file = fopen('setup_done.txt', 'w');
//Start the installer
}`

I know the code is ugly because I've wrote it inside the GitHub web interface

I don't know what you mean with a password but you could handle it with a php variable which is being included from another file and then simply compare the user input with the variable. If it matches then `wipe_db($conn);` is being executed
